config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#index'
  resources :users
  resources :brands
  resources :categories

  resources :employees do
    resources :issues, only: %i[new create]
    get 'view_issues', to: 'employees#view_issues'
  end

  resources :issues, only: %i[index edit update destroy]
  resources :items do
    member do
      delete :delete_attachment
    end
  end
  resources :storages
  resources :employees_items
  resources :user_sessions, only: %i[new destroy]
  get '/login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'
  resources :employee_sessions, only: [:destroy]
  get 'employee_logout', to: 'employee_sessions#destroy'
  get 'auth/:provider/callback', to: 'user_sessions#google_auth'
  get 'auth/failure', to: redirect('/')
end

app/models/employee.rb
# frozen_string_literal: true

# model for employee
class Employee < ApplicationRecord
  before_save :email_downcase

  has_and_belongs_to_many :items
  has_many :issues, dependent: :destroy
  has_many :employee_notifications

  validates :name, presence: true, format: /\A([a-zA-Z]|[a-zA-Z][. ])+\z/
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
  validates :status, inclusion: { in: [true, false] }

  def employee_status
    status ? 'Active' : 'Inactive'
  end

  def self.from_omniauth(auth)
    return unless Employee.find_by(email: auth.info.email)

    where(email: auth.info.email).first_or_initialize do |user|
      user.name = auth.info.name
      user.email = auth.info.email
    end
  end

  private

  def email_downcase
    self.email = email.downcase
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

# employee controller manages employee views
class EmployeesController < ApplicationController
  before_action :check_employee_access, only: %i[index new create edit update destroy]
  before_action :check_correct_show_access, only: [:show]
  before_action :check_correct_issue_access, only: [:view_issues]

  def index
    @employees = Employee.includes(:items).all
  end

  def view_issues
    @issues = Issue.where(employee_id: params[:employee_id]).includes(item: %i[brand category])
  end

  def show
    @employee = Employee.find(params[:id])
    @assigned_items = EmployeesItem.where(employee_id: @employee.id).includes(item: %i[brand category])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      AccountMailer.with(user: @employee).new_user_email.deliver_now
      redirect_to employees_path, flash: { success: 'Employee created Successfully' }
    else
      render 'new'
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path, flash: { success: 'Employee Updated Successfully' }
    else
      render 'edit'
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.items&.each do |item|
      item.storage.increment!(:quantity)
    end
    @employee.destroy
    redirect_to employees_path, flash: { success: 'Employee deleted Successfully' }
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :email, :status)
  end

  def check_employee_access
    redirect_to root_path, flash: { danger: 'Not allowed to access' } if !user_logged_in || !user_section.employee
  end

  def check_correct_show_access
    @employee = Employee.find(params[:id])
    return if employee_logged_in && @employee.id == current_employee.id

    redirect_to root_path, flash: { danger: 'Not allowed to access' }
  end

  def check_correct_issue_access
    @employee = Employee.find(params[:employee_id])
    return if (employee_logged_in && @employee.id == current_employee.id) || (user_logged_in && user_section.employee)

    redirect_to root_path, flash: { danger: 'Not allowed to access' }
  end
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

# helper contains method to access all employees
module EmployeesHelper
  def access_employees
    @employees = Employee.all
  end
end

app/views/employees/_form.html.erb
<div class="form">
  <div class="jumbotron">
    <%= form_with model: @employee do |f| %>
      <%= render 'shared/errors', object: f.object %>
      <div>
        <%= f.label :name do %>
          Name<span class="required">*</span>
        <% end %>
        <%= f.text_field :name, class:"form-control",required: true, minlength:4 %>
      </div>
      <div>
        <%= f.label :email do %>
          Email<span class="required">*</span>
        <% end %>
        <%= f.email_field :email,class:"form-control",required: true %>
      </div>
      <div>
        <%= f.label :status,class:'Dropdown' %><span class="required">*</span><br/>
        <%= f.select :status, [['Active',true], ['Inactive',false]],class:'form-control' %>
      </div><br/><br/>
      <%= f.submit yield(:button_text), class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/employees/_links.html.erb
<%= link_to "Add New Employee",new_employee_path,class:'btn btn-primary' %>

app/views/employees/edit.html.erb
<% provide(:button_text, 'Update Employee') %>
<h2 class="text-center">Edit Employee</h2>
<%= render 'form' %>

app/views/employees/index.html.erb
<%= render 'links' %>
<h3>View All Employees </h3>
<%= render 'shared/flash' %>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Status</th>
      <th scope="col">Items</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.employee_status %></td>
        <td>
        <% if employee.items.empty? %>
          No items to show
        <% else %>
          <% employee.items.each do |item| %>
            <%= item.name%>,
          <% end %>
        <% end %>
        <td><%= link_to "Edit Employee",edit_employee_path(employee), class:"btn btn-primary" %></td>
        <td><%= link_to "Delete",employee,method: :delete,data: {confirm: "Are You sure?"},class:"btn btn-danger" %></td>
      </tr>        
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<% provide(:button_text, 'Create Employee') %>
<h2 class="text-center">Add Employee</h2>
<%= render 'form' %>

app/views/employees/show.html.erb
<%= render 'shared/flash' %>
<div class="jumbotron">
<h2 class="text-center font-weight-bold">Employee Details</h2>
<p class="text-center">Name: <%= @employee.name %></p>
<p class="text-center">Email: <%= @employee.email %></p>
<p class="text-center">Status: <%= @employee.employee_status %></p>
</div>
<% if employee_logged_in %>
  <%= link_to "Assign Issue",new_employee_issue_url(@employee), class:"btn btn-danger" %>
<% end %>
<%= link_to "View Employee Issues",employee_view_issues_url(@employee), class:"btn btn-primary" %>
<h3>Items Owned</h3>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th scope="col">Brand</th>
      <th scope="col">Category</th>
      <th scope="col">Item</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <% if !@assigned_items.empty? %>
      <% @assigned_items.each do |assigned| %>
        <tr>
          <td><%= assigned.item.brand.name %></td>
          <td><%= assigned.item.category.name %></td>
          <td><%= assigned.item.name %></td>
          <td><%= assigned.item_status %></td> 
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td>No Items To Show</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/view_issues.html.erb
<% if @issues.empty? %>
  <div class="jumbotron">
    <h2>No issues to show</h2>
  </div>
<% else %>
  <% @issues.each do |issue| %>
    <div class="jumbotron">
      <p>Item: <%= issue.item.item_fullname %></p>
      <%= render 'issues/issue', issue: issue %>
    </div>
  <% end %>
<% end %>