config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#index'
  resources :users
  resources :brands
  resources :categories

  resources :employees do
    resources :issues, only: %i[new create]
    get 'view_issues', to: 'employees#view_issues'
  end

  resources :issues, only: %i[index edit update destroy]
  resources :items do
    member do
      delete :delete_attachment
    end
  end
  resources :storages
  resources :employees_items
  resources :user_sessions, only: %i[new destroy]
  get '/login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'
  resources :employee_sessions, only: [:destroy]
  get 'employee_logout', to: 'employee_sessions#destroy'
  get 'auth/:provider/callback', to: 'user_sessions#google_auth'
  get 'auth/failure', to: redirect('/')
end

app/models/item.rb
# frozen_string_literal: true

# model for item
class Item < ApplicationRecord
  before_save :name_titleize

  belongs_to :brand
  belongs_to :category

  has_one_attached :file

  has_one :storage, dependent: :destroy

  has_many :issues, dependent: :destroy

  has_and_belongs_to_many :employees

  validates :notes, presence: true, length: { maximum: 250 }
  validates :buffer_quantity, presence: true

  validates :name, presence: true,
                   uniqueness: { scope: %i[brand_id category_id], case_sensitive: false, message: 'Item present' }

  def item_fullname
    "#{brand.name} #{category.name} #{name}"
  end

  private

  def name_titleize
    self.name = name.titleize
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# items controller manages views related to items
class ItemsController < ApplicationController
  before_action :check_user_access, only: %i[index show new create edit update destroy]
  before_action :access_category_and_brand

  def index
    @items = Item.includes(:brand, :category, :storage).all
  end

  def show
    @item = Item.find(params[:id])
    @assigned_employees = EmployeesItem.where(item_id: @item.id).includes(:employee)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.name = @item.name.downcase
    @item.file.attach(params[:item][:file])
    if @item.save
      redirect_to items_path, flash: { success: 'Item added successfully' }
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path, flash: { success: 'Item updated successfully' }
    else
      render 'edit'
    end
  end

  def delete_attachment
    @image = Item.find(params[:id]).file
    # @image = ActiveStorage::Blob.find(params[:id])
    @image.purge
    redirect_back(fallback_location: root_path)
  end

  def destroy
    if Item.find(params[:id]).employees.count < 1
      Item.find(params[:id]).destroy
      redirect_to items_path, flash: { success: 'Item deleted successfully' }
    else
      redirect_to items_path, flash: { danger: 'Item assigned to employee,cannot be deleted' }
    end
  end

  private

  def item_params
    params.require(:item).permit(:name.downcase, :brand_id, :category_id, :notes, :buffer_quantity, :file)
  end

  def access_category_and_brand
    @brands = Brand.all
    @categories = Category.all
  end

  def name_downcase
    name.downcase!
  end

  def check_user_access
    redirect_to root_path, flash: { danger: 'Not allowed to access' } if !user_logged_in || !user_section.item
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

# helper contains item and admin notification
module ItemsHelper
  def access_items
    @items = Item.includes(:brand, :category).all
  end

  def admin_notifications(item)
    @admins = User.where(admin: true)
    if item.storage.quantity < 1
      create_admin_notification @admins, item.storage, 'Check ASAP', 'high'
      flash[:danger] = 'Check your storage immediately'
    elsif item.storage.quantity < item.buffer_quantity
      create_admin_notification @admins, item.storage, 'Check at a prior date', 'medium'
      flash[:warning] = 'Check your storage before the item runs out!'
    end
  end

  def create_admin_notification(admins, storage, content, priority)
    admins.each do |admin|
      AdminNotification.create!(user: admin, storage: storage, content: content, priority: priority)
    end
  end
end

app/views/items/_form.html.erb
<div class="form">
  <div class="jumbotron">
    <%= form_with model: @item do |f| %>
      <%= render 'shared/errors', object: f.object %>
      <%= f.label :name %><span class="required">*</span>
      <%= f.text_field :name.downcase, class:"form-control",required: true,minlength: 3 %>
      <%= f.label :brand_id,"Select brand" %><span class="required">*</span>
      <div>
        <%= f.select :brand_id,
              options_from_collection_for_select(Brand.all, "id", "name", f.object.brand_id), 
              prompt: "Select Brand" %>
      </div>
      <%= f.label :category_id, "Select Category" %><span class="required">*</span>
       <%= f.select :category_id,
              options_from_collection_for_select(Category.all, "id", "name", f.object.category_id), 
              prompt: "Select Category" %>
      <%= f.label :notes %><span class="required">*</span>
      <%= f.text_field :notes, class:"form-control",required: true,minlength: 4 %>
      <%= f.label :buffer_quantity,"Required Buffer" %><span class="required">*</span>
      <%= f.number_field :buffer_quantity, class:"form-control", required: true %><br/>
      <% if f.object.file.attached? %>
        <%= link_to "View Attached File", f.object.file, class: "btn btn-primary", target: "_blank" %>
        <%= link_to 'Remove File', delete_attachment_item_path(f.object.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },class: "btn btn-danger" %><br/>
      <% else %>
        <%= f.label :file,"Add Document" %>
        <%= f.file_field :file,accept:".png,.jpg,.doc,.pdf,.docx" %>
      <% end %>
      <br/>
      <%= f.submit yield(:button_text), class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/_links.html.erb
<%= link_to "Add New Item",new_item_path,class:'btn btn-primary' %>

app/views/items/edit.html.erb
<% provide(:button_text,"Edit Item") %>
<h2 class="text-center">Edit The Item</h3>
<%= render 'form' %>

app/views/items/index.html.erb
<%= render 'links' %>
<h3>View All Items </h3>
<%= render 'shared/flash' %>
<%= link_to "Assign Item To Employee",new_employees_item_path, class:"btn btn-default" %>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
    <th>Id</th>
      <th scope="col">Brand</th>
      <th scope="col">Category</th>
      <th scope="col">Item</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each_with_index do |item, index| %>
      <tr>
        <td><%= link_to index+1, item %></td>
        <td><%= item.brand.name %></td>
        <td><%= item.category.name %></td>
        <td>
          <%= item.name %>
          <% if !item.storage %>
            <span class="text-warning">(item not been assigned to storage yet)</span>
          <% end %>
        </td>
        <td><%= link_to "Edit Item",edit_item_path(item), class:"btn btn-primary" %></td>
        <% if !item.employees.exists? %>
          <td><%= button_to "Delete",item,method: :delete,data: {confirm: "Are You sure?"},class:"btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<% provide(:button_text,"Add Item") %>
<h2 class="text-center">Add An Item</h3>
<%= render 'form' %>

app/views/items/show.html.erb
<%= render 'shared/flash' %>
<div class="jumbotron">
  <h2>Item Details</h2>
  <p>Brand: <%= @item.brand.name %></p>
  <p>Category: <%= @item.category.name %></p>
  <p>Item: <%= @item.name %></p>
  <p>Notes: <%= @item.notes %></p>
  <p>Buffer Quantity: <%= @item.buffer_quantity %></p>
  <%= link_to "Download Attached File", @item.file, class: "btn btn-primary", target: "_blank" if @item.file.attached? %>
</div>
<h3>Employees having this item</h3>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Employee</th>
      <th scope="col" colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @assigned_employees.each do |assigned| %>
      <tr>
        <td><%= assigned.employee.name %></td>
        <td><%= assigned.employee.email %></td>
        <td><%= link_to "Delete", assigned,method: :delete,data: {confirm: "Are You sure?"},class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>