config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#index'
  resources :users
  resources :brands
  resources :categories

  resources :employees do
    resources :issues, only: %i[new create]
    get 'view_issues', to: 'employees#view_issues'
  end

  resources :issues, only: %i[index edit update destroy]
  resources :items do
    member do
      delete :delete_attachment
    end
  end
  resources :storages
  resources :employees_items
  resources :user_sessions, only: %i[new destroy]
  get '/login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'
  resources :employee_sessions, only: [:destroy]
  get 'employee_logout', to: 'employee_sessions#destroy'
  get 'auth/:provider/callback', to: 'user_sessions#google_auth'
  get 'auth/failure', to: redirect('/')
end

app/models/brand.rb
# frozen_string_literal: true

# model for brand
class Brand < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  scope :order_by_name, -> { order('name ASC') }
end

app/controllers/brands_controller.rb
# frozen_string_literal: true

# brands controller manages brands view
class BrandsController < ApplicationController
  before_action :check_brand_access, only: %i[index new create edit update destroy]

  def index
    @brands = Brand.order_by_name.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to brands_path, flash: { success: 'Brand added successfully' }
    else
      render 'new'
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
      redirect_to brands_path, flash: { success: 'Brand updated successfully' }
    else
      render 'edit'
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    if check_employee_association @brand
      @brand.destroy
      redirect_to brands_path, flash: { success: 'Brand deleted successfully' }
    else
      redirect_to brands_path, flash: { danger: 'Employee has an item related to this brand' }
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

  def check_brand_access
    redirect_to root_path, flash: { danger: 'Not allowed to access' } if !user_logged_in || !user_section.brand
  end
end

app/views/brands/_form.html.erb
<div class="form">
  <div class="jumbotron">
    <%= form_with model: @brand do |f| %>
      <% unless f.object.nil? %>
        <%=render 'shared/errors',object: f.object %>
      <% end %>
      <%=f.label :name do %>
        Brand Name<span class="required">*</span>
      <% end %>
      <%= f.text_field :name, class:"form-control input-sm",required: true, minlength:3 %>
      <br/>
      <%= f.submit yield(:button_text),class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/brands/edit.html.erb
<% provide(:button_text,'Update Brand') %>
<h2 class="text-center">Edit brand</h2>
<%= render 'shared/flash' %>
<%= render 'form' %>

app/views/brands/index.html.erb
<%= render 'shared/flash' %>
<%= link_to "Add Brand",new_brand_path, class:'btn btn-primary' %>
<h1>All Brands</h1>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand| %>
       <tr>
        <td><%= brand.name %></td>
        <td><%= link_to "Edit Brand",edit_brand_path(brand),class:"btn btn-primary" %></td>
        <td><%= link_to "Delete Brand", brand,method: :delete, data:{confirm:"are you sure?"},class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/brands/new.html.erb
<% provide(:button_text,'Add Brand') %>
<h2 class="text-center">Add A brand</h2>
<%= render 'form' %>